name: Build CSV IDF with Date Filter

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date limite (ex: 1962-12-31, 31-12-1962, 1962)'
        required: true
        default: '1962-12-31'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Fetch IDF companies
        run: npm run fetch:idf
      - name: Filter by date
        run: npm run filter -- --date="${{ github.event.inputs.date }}"
        env:
          PAPPERS_API_KEY: ${{ secrets.PAPPERS_API_KEY }}
      - name: Commit output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add input/*.csv || true
          git add output/*.csv || true
          git commit -m "update CSV IDF (dirigeants avant ${{ github.event.inputs.date }})" || true
          git push